ssh_allow_agent_forwarding: true                                                                         
ssh_allow_tcp_forwarding: true                                                                      
ssh_permit_tunnel: 'yes' 
