---
- hosts: emacs_servers
  become: yes
  
  vars:
    - venv: /usr/bin/.emacs.venv
      
  tasks:
   - name: Ensure virtualenv is installed.
     package:
       name: virtualenv
       state: present

   - name: Ensure EMACS is installed.
     package:
         name: emacs
         state: present

   - name: Get user's home path.
     ansible.builtin.user:
       name: "{{ ansible_user }}"
       state: present
     register: user_info
     check_mode: true  # Important, otherwise user will be created

   - name: Copy EMACS configuration.
     template:
       src: "emacs/.emacs"
       dest: "{{ user_info.home }}/.emacs"
     tags:
       - always       

- import_playbook: "emacs/provision-emacs-dependencies.yaml"
