---
- hosts: all
  become: yes

  tasks:
    - name: Run the equivalent of "apt-get update".
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install dependencies.
      package:
        name:
          - rustc
          - cargo
          - git
          - pkg-config
          - openssl
          - librust-openssl-sys-dev
          - libpam0g-dev
          - librust-pam-sys-dev
        state: present

    - name: Ensure PAM RSSH source code is downloaded.
      ansible.builtin.git:
        repo: 'https://github.com/z4yx/pam_rssh'
        dest: /tmp/pam_rssh
        version: 436bedb4a06e25ab5f35754e7ab4ab26a794f664

    - name: Compile PAM RSSH.
      command:
        chdir: /tmp/pam_rssh
        argv:
          - cargo
          - build
          - --release
        creates: /tmp/pam_rssh/target/release/libpam_rssh.so

    - name: Install PAM RSSH.
      ansible.builtin.copy:
        src: /tmp/pam_rssh/target/release/libpam_rssh.so
        dest: /lib/x86_64-linux-gnu/security/libpam_rssh.so
        remote_src: true
      become: yes

    - name: Ensure pam is configured.
      template:
        src: templates/sudo.pam
        dest: /etc/pam.d/sudo
      become: yes
      
    - name: Ensure sudo timeout is configured.
      lineinfile:
        line: Defaults        timestamp_timeout=0
        path: /etc/sudoers
      become: yes
      
    - name: Ensure sudo env is configured.
      lineinfile:
        line: Defaults        env_keep += "SSH_AUTH_SOCK"
        path: /etc/sudoers
      become: yes
      
    - name: Ensure there is no cloud init sudo file.
      ansible.builtin.file:
        path: /etc/sudoers.d/90-cloud-init-users
        state: absent
      become: yes

