- hosts: all
  become: yes

  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400 #One day

  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening   
  vars:
    ssh_allow_agent_forwarding: true
    ssh_allow_tcp_forwarding: remote
