- hosts: all
  become: yes

  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400 #One day

  roles:
    - name: devsec.hardening.os_hardening
  vars:
    os_pam_enabled: true