---
- hosts: all
  pre_tasks:
  - name: Disable sudo for the time of playbook run
    become: yes
    copy:
      dest: /etc/sudoers.d/ansible
      content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
      
  # post_tasks:
  # - name: Enable sudo back
  #   become: yes
  #   file:
  #     path: /etc/sudoers.d/ansible
  #     state: absent

- import_playbook: "provision-rssh.yaml"
- import_playbook: "provision-emacs.yaml"
- import_playbook: "provision-prometheus.yaml"
- import_playbook: "provision-sec.yaml"