---
- name: Configure servers
  block:
    - name: Update and upgrade apt packages
      apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400 #One day

    - name: install cryptography python package
      ansible.builtin.package:
        name: python3-cryptography
        state: present

    - name: Set up CA
      block:
        - name: Check whether private key exists
          stat:
                path: /etc/ssl/private/ca-prometheus.key
          register: ca_private_key_info

        - name: Create private key
          community.crypto.openssl_privatekey:
            path: /etc/ssl/private/ca-prometheus.key
          when: not ca_private_key_info.stat.exists
          no_log: true

        - name: Create certificate signing request (CSR) for CA certificate
          community.crypto.openssl_csr_pipe:
            privatekey_path: /etc/ssl/private/ca-prometheus.key
            common_name: Prometheus CA
            use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
            basic_constraints:
              - 'CA:TRUE'
            basic_constraints_critical: true
            key_usage:
              - keyCertSign
            key_usage_critical: true
            subject_alt_name:
              - "DNS:{{ inventory_hostname }}"
              - "DNS:www.{{ inventory_hostname }}"
          register: ca_csr
          no_log: true 

        - name: Check whether CA cert exists
          stat:
            path: /etc/ssl/certs/ca-prometheus.pem
          register: ca_cert_info

        - name: Create self-signed CA certificate from CSR
          when: not ca_cert_info.stat.exists            
          community.crypto.x509_certificate:
            path: /etc/ssl/certs/ca-prometheus.pem
            csr_content: "{{ ca_csr.csr }}"
            privatekey_path: /etc/ssl/private/ca-prometheus.key
            provider: selfsigned    
          no_log: true

