---
- hosts: all
  become: true
  
  pre_tasks:
    - set_fact:
        server_name: "{{ groups['prometheus_servers'][0] }}"
          
    - include_tasks: "set-up-node-exporter-cert.yaml"

  roles:
    - prometheus.prometheus.node_exporter
    
  vars:
    node_exporter_web_listen_address: "{{ inventory_hostname }}:9100"
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.pem
      key_file: /etc/node_exporter/tls.key

      