---
- hosts: all
  become: yes

  vars:
    - venv: /usr/bin/.emacs.venv
      
  tasks:
  - name: Ensure virtualenv is installed.
    package:
      name: virtualenv
      state: present
      
  - name: Ensure LSP server is installed.
    pip:
      name: python-lsp-server[all]
      virtualenv: "{{ venv }}"
      
  - name: Ensure LSP Python plugins are installed.
    pip:
      name:
        - python-lsp-black
        - python-lsp-ruff
        - python-lsp-isort
        - black
        - ruff
        - isort
      virtualenv: "{{ venv }}"

  # Required for C lsp
  - name: Ensure Clang 15 is installed.
    package:
      name: clangd-15
      state: present

  # Required for C project command generation
  # example:
  #  https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/#project-setup
  - name: Ensure Bear is installed.
    package:
      name: bear
      state: present

  - name: Ensure NPM is installed.
    comand: apt-get install npm --no-install-suggests --no-install-recommends -y

  - name: Ensure YAML lsp is installed.
    community.general.npm:
      name: yaml-language-server
      global: true


